### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Rulikkk** [axodotdev/oranda-js#2]
1. "Home" link is broken
2. "Deployment" link is broken

(links are just below the 🐟 fish emoji)

Links are broken on both pages
- https://axodotdev.github.io/oranda/ 
- https://axodotdev.github.io/oranda/deployment.html

Seems the site expects to live under https://axodotdev.github.io/ while it is actually under https://axodotdev.github.io/oranda/

**Comment by SaraVieira** [comment]
Heeey!

Thank you for letting me know! Weirdly I do have this feature in the config but forgot to add the setting for it on my own config

Fixed here https://github.com/axodotdev/oranda/commit/b8846dd6766d16c91dc6acfdcb222e35a5222fca
